### ISSUE TITLE
No deployment description directory

### ISSUE THREAD

**Issue by haxdai** [ferhura/POSE#1]
No se subió al repositorio el descriptor de despliegue del proyecto. Netbeans no sabe cómo hacer el build y deploy.

<img width="657" alt="captura de pantalla 2016-05-30 a las 4 53 18 p m" src="https://cloud.githubusercontent.com/assets/7064389/15658845/1bd47640-2687-11e6-96fb-cd8307d4a91b.png">

Esto significa básicamente que falta la carpeta WEB-INF.
Para evitar esto:

````bash
cd POSE
touch web/WEB-INF/.gitignore
git add web/WEB-INF/.gitignore
git commit -am "Agregado gitignore"
git push
````

**Comment by gabydhi** [comment]
Listo.
