### ISSUE TITLE
Desarrollar funcionalidad de inicio de sesión

### ISSUE THREAD

**Issue by ferhura** [ferhura/POSE#2]
Desarrollar funcionalidad de inicio de sesión con base en documento de especificación del sistema. @gabydhi

**Comment by gabydhi** [comment]
Lista la parte gráfica

**Comment by haxdai** [comment]
La clase Login.java de SWB implementa el servlet de loggeo en SWBPortal. Quizás pueda ayudar a no partir de cero en algunas cosas.

[http://svn.semanticwebbuilder.org.mx/SemWB4/SWB4/swb/SWBPortal/src/org/semanticwb/servlet/internal/Login.java](http://svn.semanticwebbuilder.org.mx/SemWB4/SWB4/swb/SWBPortal/src/org/semanticwb/servlet/internal/Login.java)

Saludos!

**Comment by haxdai** [comment]
Los issues que sean nuevos features podríamos redactarlos como historias tipo SCRUM, ejemplo:

- Como usuario normal o administrador puedo acceder al sistema proporcionando un nombre de usuario y una contraseña.

**Comment by ferhura** [comment]
De acuerdo Ebenezer.
